NAME: 'cvppp'

MODEL:
    input_nc: 3
    output_nc: 2
    if_sigmoid: False
    emd: 16
    filters: 
        - 16
        - 32
        - 64
        - 128
        - 256
    finetuning: False

TRAIN:
    resume: False
    if_valid: True
    if_seg: True
    cache_path: '../caches/'
    save_path: '../models/'
    loss_func: 'WeightedMSELoss'   # 'WeightedBCELoss', 'BCELoss'
    affs0_weight: 1
    mask_weight: 0.0
    dis_mode: 'ours'
    ema: False
    ema_decay: 0.99
    sharing_weights: True
    self_emb: 1.0
    cross_emb: 1.0
    ct_weight: 0.0
    deep_weight: 1

    opt_type: 'adam'  # sgd
    lr_mode: 'fixed'
    total_iters: 200000
    warmup_iters: 0
    base_lr: 0.0001
    end_lr: 0.0001
    display_freq: 100
    show_freq: 1000
    valid_freq: 1000
    save_freq: 1000
    decay_iters: 100000
    weight_decay: ~
    power: 1.5

    batch_size: 2
    num_workers: 2
    if_cuda: True

    random_seed: 555  # -1 is none

DATA:
    valid_set: 'local_20_1'
    aug_mode: 'xiaoyu' # rsis, xiaoyu
    remove_training_set: ~
    if_ema_noise: False
    if_ema_blur: False
    if_ema_intensity: True
    if_ema_mask: True
    if_ema_flip: True
    size: 544
    num_train: 108
    data_folder: '../data/CVPPP'
    padding: True
    separate_weight: True
    background: False
    shifts:
        - 1
        - 3
        - 5
        - 9
        - 27
    neighbor: 4
    strides: 
        - 5
        - 5
    if_dilate: True
    widen_way: True
    if_scale_aug: True
    if_filp_aug: True
    if_rotation_aug: True
    if_intensity_aug: True
    if_elastic_aug: True

TEST:
    pad: 0
    model_name: ''